"""Plot the main results generated by the thesis replication suite."""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg") # don't create window.
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


METHOD_COLOURS = {"ELM-FBPINN": "tab:blue", "Shifted FEM": "tab:orange"}

def _save(fig, output_dir, name):
    fig.savefig(Path(output_dir) / f"{name}.png", dpi=240, bbox_inches="tight")
    plt.close(fig)

def _method_curve(ax, frame, metric, order, label_suffix=""):
    for method in ("ELM-FBPINN", "Shifted FEM"):
        selected = frame[(frame["method"] == method) & (frame["order"] == order)]
        if selected.empty:
            continue
        grouped = selected.groupby("J")[metric]
        centre = grouped.mean()
        label = f"{method}, " + (rf"$K={order**2}$" if method == "ELM-FBPINN"
                                      else rf"$Q_{order}$") + label_suffix
        style = "-" if order == 1 else "--"
        ax.plot(centre.index, centre.values, style, marker="o", linewidth=1.5,
                color=METHOD_COLOURS[method], label=label)
        if method == "ELM-FBPINN" and selected["seed"].nunique() > 1:
            ax.fill_between(centre.index, grouped.min().values, grouped.max().values,
                            color=METHOD_COLOURS[method], alpha=0.16)

def plot_refinement(summary, output_dir, name):
    metrics = (("normalised_l1", "normalised $L^1$ error"),
               ("relative_l2", "relative $L^2$ error"),
               ("maximum", "maximum absolute error"))
    fig, axes = plt.subplots(1, 3, figsize=(11.5, 3.4), constrained_layout=True)
    for ax, (metric, ylabel) in zip(axes, metrics):
        for order in sorted(summary["order"].unique()):
            _method_curve(ax, summary, metric, int(order))
        ax.set(xlabel="subdomains per direction $J$", ylabel=ylabel, yscale="log")
        ax.grid(alpha=0.22, which="both")
    axes[0].legend(frameon=False, fontsize=7)
    _save(fig, output_dir, name)

def plot_solution_fields(results, output_dir):
    cases = ((8, 1), (2, 3), (4, 3), (8, 3))
    fig, axes = plt.subplots(len(cases), 5, figsize=(15.5, 2.55 * len(cases)),
                             constrained_layout=True, squeeze=False)
    headings = ("Exact", "ELM-FBPINN", "ELM absolute error",
                "Shifted FEM", "FEM absolute error")
    for row, (J, order) in enumerate(cases):
        elm = results.elm_run(J, order, seed=0).prediction
        fem = results.fem_run(J, order).prediction
        fields = (results.exact, elm, np.abs(elm-results.exact),
                  fem, np.abs(fem-results.exact))
        for column, (ax, values) in enumerate(zip(axes[row], fields)):
            limits = {"vmin": 0.0, "vmax": 1.0} if column in {0, 1, 3} else {}
            image = ax.pcolormesh(results.X, results.Y,
                                  np.asarray(values).reshape(results.X.shape),
                                  shading="auto", cmap="viridis", **limits)
            ax.set(title=headings[column] if row == 0 else "",
                   xlabel="$x$", ylabel="$y$", aspect="equal")
            colourbar = fig.colorbar(image, ax=ax, fraction=0.046)
            colourbar.set_label(r"$u$" if column in {0, 1, 3}
                                else r"$|u-u_h|$")
        axes[row, 0].set_ylabel(rf"$J={J}$, ELM $K={order**2}$, FEM $Q_{order}$"
                                + "\n$y$")
    _save(fig, output_dir, "poisson_solution_selected")

def plot_matrix_patterns(results, output_dir):
    fig, axes = plt.subplots(2, 3, figsize=(9.4, 6.0), constrained_layout=True)
    for row, order in enumerate((1, 3)):
        elm = results.elm_run(4, order, seed=0).matrix
        fem = results.fem_run(4, order).matrix
        matrices = (elm, elm.T @ elm, fem)
        titles = (r"ELM $M$", r"ELM $M^{\mathrm{T}}M$", rf"shifted $Q_{order}$ FEM $A$")
        for ax, matrix, title in zip(axes[row], matrices, titles):
            ax.spy(matrix, markersize=max(0.25, 2.0 / order))
            ax.set_title(title, fontsize=9)
            ax.set_xlabel("coefficient index")
            ax.set_ylabel("row index" if matrix is elm else "coefficient index")
    _save(fig, output_dir, "coefficient_matrices")

def plot_conditioning(summary, output_dir):
    fig, ax = plt.subplots(figsize=(5.8, 3.8), constrained_layout=True)
    for order in sorted(summary["order"].unique()):
        for method in ("ELM-FBPINN", "Shifted FEM"):
            selected = summary[(summary["method"] == method)
                               & (summary["order"] == order)]
            grouped = selected.groupby("J")["condition"].mean()
            ax.plot(grouped.index, grouped.values,
                    "-" if order == 1 else "--", marker="o",
                    color=METHOD_COLOURS[method],
                    label=f"{method}, " + (rf"$K={int(order)**2}$"
                                           if method == "ELM-FBPINN"
                                           else rf"$Q_{int(order)}$"))
    ax.set(xlabel="subdomains per direction $J$", ylabel="condition number",
           yscale="log")
    ax.grid(alpha=0.22, which="both")
    ax.legend(frameon=False, fontsize=7, ncol=2)
    _save(fig, output_dir, "poisson_conditioning")

def plot_polynomial_sampling(summary, output_dir):
    elm = summary[summary["method"] == "ELM-FBPINN"]
    fig, axes = plt.subplots(1, 2, figsize=(8.2, 3.4), constrained_layout=True)
    for factor in sorted(elm["sampling_factor"].unique()):
        selected = elm[elm["sampling_factor"] == factor].sort_values("J")
        label = rf"sampling factor ${int(factor)}$"
        axes[0].plot(selected["J"], selected["normalised_l1"], marker="o", label=label)
        axes[1].plot(selected["J"], selected["relative_residual"], marker="o", label=label)
    axes[0].set(xlabel="$J$", ylabel="normalised $L^1$ error", yscale="log")
    axes[1].set(xlabel="$J$", ylabel="relative residual", yscale="log")
    for ax in axes:
        ax.grid(alpha=0.22, which="both")
    axes[0].legend(frameon=False)
    _save(fig, output_dir, "polynomial_sampling")

def plot_overlap(summary, output_dir):
    elm = summary[summary["method"] == "ELM-FBPINN"]
    fig, axes = plt.subplots(1, 3, figsize=(10.8, 3.4), constrained_layout=True)
    for order in sorted(elm["order"].unique()):
        selected = elm[elm["order"] == order].sort_values("overlap")
        label = rf"$K={int(order)**2}$"
        axes[0].plot(selected["overlap"], selected["nnz"], marker="o", label=label)
        axes[1].plot(selected["overlap"], selected["normalised_l1"], marker="o", label=label)
        axes[2].plot(selected["overlap"], selected["total_time"], marker="o", label=label)
    axes[0].set(xlabel="overlap factor", ylabel="matrix nonzeros")
    axes[1].set(xlabel="overlap factor", ylabel="normalised $L^1$ error", yscale="log")
    axes[2].set(xlabel="overlap factor", ylabel="total time (s)", yscale="log")
    for ax in axes:
        ax.grid(alpha=0.22, which="both")
    axes[0].legend(frameon=False)
    _save(fig, output_dir, "overlap_sweep")

def plot_joint_scaling(summary, output_dir):
    fig, axes = plt.subplots(1, 3, figsize=(10.8, 3.4), constrained_layout=True)
    for method in ("ELM-FBPINN", "Shifted FEM"):
        selected = summary[summary["method"] == method]
        grouped = selected.groupby("omega")
        centre = grouped.mean(numeric_only=True)
        style = "-" if method == "ELM-FBPINN" else "--"
        for ax, metric in zip(axes, ("normalised_l1", "assembly_time", "solve_time")):
            ax.plot(centre.index, centre[metric], style, marker="o",
                    color=METHOD_COLOURS[method], label=method)
            if method == "ELM-FBPINN" and selected["seed"].nunique() > 1:
                ax.fill_between(centre.index, grouped[metric].min().values,
                                grouped[metric].max().values,
                                color=METHOD_COLOURS[method], alpha=0.16)
    axes[0].set(xlabel="solution frequency $\\omega$",
                ylabel="normalised $L^1$ error", yscale="log")
    axes[1].set(xlabel="solution frequency $\\omega$", ylabel="assembly time (s)", yscale="log")
    axes[2].set(xlabel="solution frequency $\\omega$", ylabel="solve time (s)", yscale="log")
    for ax in axes:
        ax.grid(alpha=0.22, which="both")
    axes[0].legend(frameon=False)
    _save(fig, output_dir, "joint_scaling")
